name: Deploy Bot Finance Infrastructure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - dev

env:
  AWS_REGION: us-east-1
  TF_VAR_environment: ${{ github.event.inputs.environment || 'prod' }}

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'prod' }}
    
    steps:
    - name: Checkout Infrastructure Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.6.0"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Format Check
      working-directory: environments/${{ env.TF_VAR_environment }}
      run: |
        echo "🔍 Verificando formato de código Terraform..."
        terraform fmt -check -recursive
        echo "✅ Formato de código correcto"

    - name: Terraform Init
      working-directory: environments/${{ env.TF_VAR_environment }}
      run: |
        echo "🚀 Inicializando Terraform..."
        terraform init
        echo "✅ Terraform inicializado correctamente"

    - name: Terraform Validate
      working-directory: environments/${{ env.TF_VAR_environment }}
      run: |
        echo "✅ Validando configuración de Terraform..."
        terraform validate
        echo "✅ Configuración válida"

    - name: Terraform Plan
      working-directory: environments/${{ env.TF_VAR_environment }}
      run: |
        echo "📋 Generando plan de despliegue..."
        terraform plan -out=tfplan
        echo "✅ Plan generado correctamente"

    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan-${{ env.TF_VAR_environment }}
        path: environments/${{ env.TF_VAR_environment }}/tfplan

  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    environment: ${{ github.event.inputs.environment || 'prod' }}
    
    steps:
    - name: Checkout Infrastructure Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.6.0"
        terraform_wrapper: false

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Download Plan Artifact
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan-${{ env.TF_VAR_environment }}
        path: environments/${{ env.TF_VAR_environment }}

    - name: Terraform Init
      working-directory: environments/${{ env.TF_VAR_environment }}
      run: |
        echo "🚀 Inicializando Terraform..."
        terraform init
        echo "✅ Terraform inicializado correctamente"

    - name: Terraform Apply
      working-directory: environments/${{ env.TF_VAR_environment }}
      run: |
        echo "🔧 Desplegando infraestructura..."
        terraform apply -auto-approve tfplan
        echo "✅ Infraestructura desplegada correctamente"

    - name: Deployment Summary
      run: |
        echo "🎉 ¡Deployment completado exitosamente!"
        echo "=========================="
        echo "🌍 Environment: ${{ env.TF_VAR_environment }}"
        echo "📦 Recursos creados según la configuración en main.tf"
        echo ""
        echo "⚙️ Próximos pasos:"
        echo "   - Verificar recursos en AWS Console"
        echo "   - Configurar manualmente valores sensibles si es necesario"
        echo "   - Revisar documentación en CONFIGURACION_MANUAL.md"

  notify:
    name: Notify Deployment Status
    runs-on: ubuntu-latest
    needs: [validate, deploy]
    if: always()
    
    steps:
    - name: Notify Success
      if: needs.deploy.result == 'success'
      run: |
        echo "✅ Deployment exitoso para environment: ${{ env.TF_VAR_environment }}"
        
    - name: Notify Failure
      if: needs.deploy.result == 'failure'
      run: |
        echo "❌ Deployment falló para environment: ${{ env.TF_VAR_environment }}"
        echo "Revisa los logs para más detalles"
